### ISSUE TITLE
Unable to display Latex on foot terminal

### ISSUE THREAD

**Issue by MightyPlaza** [joouha/euporie#101]
Using version 2.7.0, on foot terminal, I am unable to render anything with Latex (`IPython.display` or Markdown).
Using `matplotlib.pyplot` plots a graph as expected
On kitty everything works as expected
(behaviour does not change for foot or kitty with/without `"graphics": "sixel"`)
Unsure if this is an issue with my system

Other minor (unrelated) issues I've found:
- I can't seem to create any files without explicitly adding the `.ipynb` extension. euporie shows `Saving...` permanently
- Changing color scheme to `custom` without having the colors set up results in a lockdown and a cpu core being at 100%. Killing the program and trying to start it, results in an error
- Can anything be done for euporie to work with NumLock enabled? (https://github.com/joouha/euporie/issues/94)

Thanks for awesome project

**Comment by joouha** [comment]
Hi,

1. If LaTeX rendering is working as expected in kitty, you probably need to install a program which can convert from png to sixel, such as `chafa`, `imagemagick`, or the `chafa.py` python package.

   Kitty can display `png` images directly using the kitty graphics protocol, whereas foot can only display sixel graphics, so euporie needs some way to convert images into sixels.

2. I think this file saving issue might already fixed in the `dev` branch. Could you explain exactly what's happening in a bit more detail for me?

3. I've added default values for these config options in `dev`, which should fix this 🤞

4. I'll take a look at the numlock issue tomorrow. I thought I'd already fixed it, so thanks for letting me know it's still not working!

**Comment by MightyPlaza** [comment]
>  1. If LaTeX rendering is working as expected in kitty, you probably need to install a program which can convert from png to sixel, such as `chafa`, `imagemagick`, or the `chafa.py` python package.

tried installing all 3 and restarting euporie, still no output on foot

>  2. I think this file saving issue might already fixed in the `dev` branch. Could you explain exactly what's happening in a bit more detail for me?

If I don't specify the `.ipynb` at the end of the name when creating a new file, nothing happens. It permanently says `Saving...` in the corner

**Comment by joouha** [comment]
I've just released v2.8.0, which should fix the issues reported here

**Comment by MightyPlaza** [comment]
can confirm all issues have been fixed (tab with numlock on still doesn't work, but the rest of the keys seem to work now)
thanks for the help

**Comment by joouha** [comment]
Thanks. I've released published `v2.8.1` with a (untested) fix for the tab key.

**Comment by MightyPlaza** [comment]
can confirm it works
thanks again
