### ISSUE TITLE
Stupid question: Installing from git

### ISSUE THREAD

**Issue by volkerkarle** [joouha/euporie#16]
Dear developers,

I intended to clone directly from git and install it from there, but I could not find a setup.py. How does it work?

Best,

v.

**Comment by joouha** [comment]
Hello,

No questions are stupid here :-)

Euporie uses a `pyproject.toml` file instead of a `setup.py` script. `pyproject.toml` is a new configuration file for python packages - if you want to read more about it, it is defined in [PEP 518](https://www.python.org/dev/peps/pep-0518/) and expanded in [PEP 621](https://www.python.org/dev/peps/pep-0621/). 

If you want to install from git, you can do so as follows:

```bash
git clone https://github.com/joouha/euporie.git
cd euporie
pip install .
```

You'll need a fairly up-to-date version of `pip` to install packages with `pyproject.toml` configuration files.

I should probably add some instructions for how to install from git to the `README`.

**Comment by volkerkarle** [comment]
Thanks a lot, that was new to me.
