### ISSUE TITLE
Notebook object has no attribute inspect

### ISSUE THREAD

**Issue by 875d** [joouha/euporie#48]
When I try to use the `--autoinspect` swtich, whenever I try to type something I get the following errors.
I'm using the standard ipython kernel.

![image](https://user-images.githubusercontent.com/118444583/205242337-072823d1-2450-4238-ab87-0a0d44516ff7.png)

**Comment by joouha** [comment]
Hello!

This is a bug - I've fixed it in 6df0830023f31d6d4a0d8b1cec41c1aeded748ce in `dev`, and it will be in the next release.

---

Out of interest, which OS are you using? I ask because the rectangle character the error message should be an expander arrow (`⮞` `⮟`), but it looks like you don't have a font which provides these characters. I might switch to plain triangles for better compatibility.

**Comment by 875d** [comment]
> This is a bug - I've fixed it in 6df0830 in dev, and it will be in the next release.

Thank you! I'm curious to see what that switch achieves!

> Out of interest, which OS are you using?

Arch

> I ask because the rectangle character the error message should be an expander arrow (⮞ ⮟), but it looks like you don't have a font which provides these characters. I might switch to plain triangles for better compatibility.

My kitty terminal should use Nerd Fonts, and in theory load from Symbols Nerd Fonts.

I don't know what's happening, I'm not very expert with fonts.

**Comment by joouha** [comment]
The fix for this is now in `v2.2.0`
