### ISSUE TITLE
Plots are truncated

### ISSUE THREAD

**Issue by twrightsman** [joouha/euporie#67]
Plots seem to be truncated; is there any way to fix this? See the image below:

![truncated](https://user-images.githubusercontent.com/6300973/231193903-26f7071d-1f80-41fb-be00-befea4c752f8.png)

**Comment by twrightsman** [comment]
Hello! This screenshot is using the Foot terminal inside a tmux session.

**Comment by twrightsman** [comment]
Well, I guess I spoke too soon... The following is over SSH, in a remote tmux session, using the Foot terminal on the client. `tmux_graphics` are enabled.

![truncated](https://user-images.githubusercontent.com/6300973/231237564-3235b249-1b79-40e6-9067-e8096eaa2108.png)

**Comment by twrightsman** [comment]
I did some further investigation using the latest `dev` commit (https://github.com/joouha/euporie/commit/f1cdd080e442827c69fca2bfd19f71a42642cdc1) and this seems to be a Foot terminal-specific issue...

I ran `euporie-notebook` inside of `tmux` and then joined that session from both Foot and GNOME Terminal. When I plot something through Foot, the plot is truncated. However, if I move to another cell and back to the plotted cell in GNOME Terminal, the plot resizes to the correct shape, including in the tmux session connected through Foot. Then when I move to another cell and back in Foot, the plot becomes truncated again in both terminals.

**Comment by joouha** [comment]
I believe this is because the default ANSI image renderer, [timg](https://github.com/adzierzanowski/timg), assumes a 2x1 terminal character aspect ratio.

Foot appears to favour slightly taller character aspect ratios, hence the truncated graphics.

I suggest you install [`chafa.py`](https://github.com/GuardKenzie/chafa.py) in the same environment as euporie - it's a far ANSI superior image renderer, and supports custom character aspect ratios to boot, so this should solve your issue.

I'm contemplating making `chafa.py` the default image renderer in euporie (so it gets installed as a required dependency by default).

**Comment by joouha** [comment]
Actually I think I might have now fixed the issue with `timg` in `dev` with 08f45f7568b86ee5bf811a634388800bd75957a9, by resizing images before rendering to work around the 2x1 aspect ratio assumption.

**Comment by twrightsman** [comment]
Thanks for taking another look at this; things look a lot better!

![screenshot](https://user-images.githubusercontent.com/6300973/235213085-5de026e6-3670-4328-9ebf-6ade5d0e319e.png)

Will euporie auto-detect the presence of `chafa.py` if I install it and use it over `timg`?

**Comment by twrightsman** [comment]
I'm happy to open a separate issue for this, but after installing `chafa.py` I get `(Format Conversion Error)` after plotting.

![format-conversion-error](https://user-images.githubusercontent.com/6300973/235216848-495ad907-1386-415f-928c-7b9cb30f7c34.png)

**Comment by twrightsman** [comment]
I think we can consider this fixed, thank you! I migrated the `chafa.py` bug to it's own issue.
