### ISSUE TITLE
Installation issues 

### ISSUE THREAD

**Issue by datacubeR** [joouha/euporie#94]
Hi,
I think this could be a great deal for my dev workflow, only if I manage to get it to work. So far, nothing works as expected. Here some insights:

![Screenshot from 2023-08-19 19-19-38](https://github.com/joouha/euporie/assets/48638337/ede58bde-e750-47fe-b8ea-f0142da6a8bd)

When opening euporie-notebook, the top bar just dissapears. And hitting enter does not work to edit cells. Plus keybindings using Ctrl or Shift do not work at all. 

When using euporie-console the main problem begins 

![Screenshot from 2023-08-19 19-22-32](https://github.com/joouha/euporie/assets/48638337/57657f50-3f86-49b3-afa0-5b8cc4c4dcb0)

Nothing works, and this escape characters start rendering for any key that is not a letter. I'm using Kitty, and added the remaps specified in the docs. 

The weirdest thing is that I can run Console and Notebook when using Floatterm within Neovim
![Screenshot from 2023-08-19 19-24-38](https://github.com/joouha/euporie/assets/48638337/5947bf2d-6bee-4664-ab6c-ba1ed8de2812)

But I still have some rendering issues. 

I'm using Kitty as my terminal and I installed euporie in my conda environment since I want to make use of my packages. Is there any part of the setup that I'm missing? Any guidelines would be deeply appreciated. 

Thanks,

Alfonso

**Comment by joouha** [comment]
Hi Alfonso,

Thanks for reporting this. It seems like the main issues here are:

1. Top-bar in euporie notebook disappears
2. Enter does not work to edit cells
3. Key-bindings with <kbd>Ctrl</kbd> or <kbd>Shift</kbd> do not work
4. Escape characters start rendering for any key that is not a letter

For the first issue (the top-bar disappearing) I'm not sure what causes this (obviously it works for me!). You can press <kbd><kbd>Ctrl</kbd>+<kbd>L</kbd></kbd> in euporie-notebook to redraw the screen, which should get the top-bar to show again.

I think the remaining issues are related to the [kitty keyboard protocol](https://sw.kovidgoyal.net/kitty/keyboard-protocol/). Kitty has it's own way of reporting key combinations, which it is necessary for euporie to use to detect some of its key-bindings. However, I think it's my implementation of this protocol which is causing the issues.

The reason that things work in Floatterm is because Floatterm is basically a terminal emulator which runs inside a terminal, and Floatterm does not implement kitty's keyboard protocol.

I'll see if I can get the un-recognised escape codes to stop printing to the text inputs.

- What version of kitty are you using?
- Do you mind sharing your kitty config?
- From the escape codes in your screenshot, it looks like you have numlock enabled - does anything work with numlock turned off?

Sorry for the slow reply - I've had to take a bit of time off from euporie over the summer.

Josiah

**Comment by joouha** [comment]
I think the keyboard related you were experiencing should have been fixed now.

I've also finally managed to track down and fixed the bug which causes the top bar to disappear - it should be fixed by faeb8009fde13a2bdce8df5007c00f1b895b1a9c). I'll make a new release with this fix shortly.

**Comment by joouha** [comment]
Everything should be fixed in the latest version (v2.7.0). If you're still having problems please open a new issue
